[package]
name = "events"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
# console_error_panic_hook = "0.1"
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = [
  "Document",
  "HtmlElement",
  "HtmlInputElement",
  "InputEvent",
  "Node",
  "Text",
  "Window",
] }
